//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PettingZoo.UI.Tab.Subscriber {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubscriberViewStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubscriberViewStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PettingZoo.UI.Tab.Subscriber.SubscriberViewStrings", typeof(SubscriberViewStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string CommandClear {
            get {
                return ResourceManager.GetString("CommandClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new Publisher tab.
        /// </summary>
        public static string ContextPublish {
            get {
                return ResourceManager.GetString("ContextPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-persistent.
        /// </summary>
        public static string DeliveryModeNonPersistent {
            get {
                return ResourceManager.GetString("DeliveryModeNonPersistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent.
        /// </summary>
        public static string DeliveryModePersistent {
            get {
                return ResourceManager.GetString("DeliveryModePersistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New messages.
        /// </summary>
        public static string LabelNewMessages {
            get {
                return ResourceManager.GetString("LabelNewMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string PanelTitleBody {
            get {
                return ResourceManager.GetString("PanelTitleBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PanelTitleProperties {
            get {
                return ResourceManager.GetString("PanelTitleProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PropertyName {
            get {
                return ResourceManager.GetString("PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string PropertyValue {
            get {
                return ResourceManager.GetString("PropertyValue", resourceCulture);
            }
        }
    }
}
