//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PettingZoo.UI.Tab.Publisher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PublisherViewStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PublisherViewStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PettingZoo.UI.Tab.Publisher.PublisherViewStrings", typeof(PublisherViewStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string CommandPublish {
            get {
                return ResourceManager.GetString("CommandPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        public static string LabelExchange {
            get {
                return ResourceManager.GetString("LabelExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type: .
        /// </summary>
        public static string LabelMessageType {
            get {
                return ResourceManager.GetString("LabelMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string LabelQueue {
            get {
                return ResourceManager.GetString("LabelQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply To.
        /// </summary>
        public static string LabelReplyTo {
            get {
                return ResourceManager.GetString("LabelReplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New subscriber tab.
        /// </summary>
        public static string LabelReplyToNewSubscriber {
            get {
                return ResourceManager.GetString("LabelReplyToNewSubscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified queue.
        /// </summary>
        public static string LabelReplyToSpecified {
            get {
                return ResourceManager.GetString("LabelReplyToSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing key.
        /// </summary>
        public static string LabelRoutingKey {
            get {
                return ResourceManager.GetString("LabelRoutingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to exchange (topic).
        /// </summary>
        public static string LabelSendToExchange {
            get {
                return ResourceManager.GetString("LabelSendToExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to queue (direct).
        /// </summary>
        public static string LabelSendToQueue {
            get {
                return ResourceManager.GetString("LabelSendToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw message.
        /// </summary>
        public static string OptionMessageTypeRaw {
            get {
                return ResourceManager.GetString("OptionMessageTypeRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tapeti message.
        /// </summary>
        public static string OptionMessageTypeTapeti {
            get {
                return ResourceManager.GetString("OptionMessageTypeTapeti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re: .
        /// </summary>
        public static string ReplyToCorrelationIdPrefix {
            get {
                return ResourceManager.GetString("ReplyToCorrelationIdPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish: {0}.
        /// </summary>
        public static string TabTitle {
            get {
                return ResourceManager.GetString("TabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string TabTitleEmpty {
            get {
                return ResourceManager.GetString("TabTitleEmpty", resourceCulture);
            }
        }
    }
}
