//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PettingZoo.UI.Tab.Publisher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RawPublisherViewStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RawPublisherViewStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PettingZoo.UI.Tab.Publisher.RawPublisherViewStrings", typeof(RawPublisherViewStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transient (non-persistent).
        /// </summary>
        public static string DeliveryModeNonPersistent {
            get {
                return ResourceManager.GetString("DeliveryModeNonPersistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent.
        /// </summary>
        public static string DeliveryModePersistent {
            get {
                return ResourceManager.GetString("DeliveryModePersistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string HeaderValue {
            get {
                return ResourceManager.GetString("HeaderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App ID.
        /// </summary>
        public static string LabelAppId {
            get {
                return ResourceManager.GetString("LabelAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content encoding.
        /// </summary>
        public static string LabelContentEncoding {
            get {
                return ResourceManager.GetString("LabelContentEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type.
        /// </summary>
        public static string LabelContentType {
            get {
                return ResourceManager.GetString("LabelContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation ID.
        /// </summary>
        public static string LabelCorrelationId {
            get {
                return ResourceManager.GetString("LabelCorrelationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery mode.
        /// </summary>
        public static string LabelDeliveryMode {
            get {
                return ResourceManager.GetString("LabelDeliveryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        public static string LabelExchange {
            get {
                return ResourceManager.GetString("LabelExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration.
        /// </summary>
        public static string LabelExpiration {
            get {
                return ResourceManager.GetString("LabelExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string LabelHeaders {
            get {
                return ResourceManager.GetString("LabelHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message ID.
        /// </summary>
        public static string LabelMessageId {
            get {
                return ResourceManager.GetString("LabelMessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload.
        /// </summary>
        public static string LabelPayload {
            get {
                return ResourceManager.GetString("LabelPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string LabelPriority {
            get {
                return ResourceManager.GetString("LabelPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string LabelProperties {
            get {
                return ResourceManager.GetString("LabelProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string LabelQueue {
            get {
                return ResourceManager.GetString("LabelQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply To.
        /// </summary>
        public static string LabelReplyTo {
            get {
                return ResourceManager.GetString("LabelReplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing key.
        /// </summary>
        public static string LabelRoutingKey {
            get {
                return ResourceManager.GetString("LabelRoutingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to exchange (topic).
        /// </summary>
        public static string LabelSendToExchange {
            get {
                return ResourceManager.GetString("LabelSendToExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to queue (direct).
        /// </summary>
        public static string LabelSendToQueue {
            get {
                return ResourceManager.GetString("LabelSendToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string LabelTimestamp {
            get {
                return ResourceManager.GetString("LabelTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string LabelType {
            get {
                return ResourceManager.GetString("LabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string LabelUserId {
            get {
                return ResourceManager.GetString("LabelUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏶ Collapse.
        /// </summary>
        public static string PropertiesCollapse {
            get {
                return ResourceManager.GetString("PropertiesCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏷ Expand.
        /// </summary>
        public static string PropertiesExpand {
            get {
                return ResourceManager.GetString("PropertiesExpand", resourceCulture);
            }
        }
    }
}
